### ISSUE TITLE
Charging doesn't exceed 5W

### ISSUE THREAD

**Issue by ghost** [XperiaBrickers-10IV/BUG_REPORTS#13]
On build 20230503.
Just noticed that at 60% or 70% charging is capped at 5W which I don't think is intended.
Don't think this happens on build 20230502.

**Comment by ghost** [comment]
That is normal on new phones, my pixel 7 does the same thing, it's done to protect the battery from getting damaged

**Comment by ghost** [comment]
Thanks for the clarification.
Was confused since my older phone charged differently.

**Comment by ghost** [comment]
I think charging is broken.
Phone is at 40% when charging and it's capped at 5W.
Pretty sure it shouldn't limit to 5W until it's nearly fully charged.

**Comment by ghost** [comment]
Unfortunately, the PMIC driver is broken, there isn't much that I can do at the moment

**Comment by ghost** [comment]
More information, very intermittently fast charging works. 
Today at 55% battery, plugged in and it's charging at 25W.

**Comment by ghost** [comment]
Yeah all due to broken pmic driver

**Comment by ghost** [comment]
I'm guessing it's up to sony to fix this in their source code, correct?

**Comment by SpectreDev-007** [comment]
I can't say for sure I'd need some logs to see what the issue is

**Comment by ghost** [comment]
Sure thing, give me some time to drain the battery and I'll attach one.

**Comment by ghost** [comment]
Sorry replied to wrong issue don't need a log for this, yes Sony would need to fix it

**Comment by ghost** [comment]
Kernel driver side has been fixed, now need to fix DT side

**Comment by ghost** [comment]
Thanks to Lily PMIC is fully fixed, now draws 15w constantly and charges very quickly (use kernel_sony_murray-pmic repo for kernel to have working pmic)
