### ISSUE TITLE
Audio: Alarm does not work

### ISSUE THREAD

**Issue by LecrisUT** [XperiaBrickers-10IV/BUG_REPORTS#3]
@SpectreDev-007 It would be great to have the current bugs you've mentioned [here](https://github.com/orgs/XperiaBrickers-10IV/discussions/1) as separate bugs so people can subsccribe to them to get more updates on it. Feel free to edit this top comment with relevant tracking information.

**Comment by ghost** [comment]
Nice idea thanks for that

**Comment by ghost** [comment]
Solved with Android 13 DTS
